regamedll/dlls/game.cpp
Went the command way because the cvar way (like sv_restart) seems pretty counter intuitive IMO (actions should be commands, and CVARS configurations), but feel free to edit whatever you want.
=> End round command

regamedll/build.gradle, regamedll/dlls/vector.h, regamedll/engine/common.h
Removed some unnecessary checks
=> Fixed Vector constructors

regamedll/dlls/cbase.cpp, regamedll/dlls/multiplay_gamerules.cpp, regamedll/dlls/player.cpp, regamedll/dlls/weapons.cpp
Have is resetting the mins/maxs of armoury_entity that is causing the issue with the collision.
[The video here demonstrates in detail about this.](https://www.youtube.com/watch?v=LeNk8dhR4FE)
=> Adjustment physics of amoury_entity

regamedll/regamedll/regamedll_interfaces_impl.cpp
Related to https://github.com/s1lentq/ReGameDLL_CS/issues/75
I don't know if this is the right way to fix it but at least it works well
=> Fix JoinTeam from UNA to T/CT

regamedll/dlls/hostage/hostage.cpp, regamedll/dlls/multiplay_gamerules.cpp, regamedll/extra/cssdk/dlls/regamedll_api.h, regamedll/pm_shared/pm_shared.cpp, regamedll/pm_shared/pm_shared.h, regamedll/public/regamedll/regamedll_api.h, regamedll/regamedll/regamedll_api_impl.cpp, regamedll/regamedll/regamedll_api_impl.h
Fixes #90
Fix: not ending of the round when the hostages rescued
=> ReGameDLL API: Add PM_UpdateStepSound

regamedll/dlls/bot/cs_bot_init.cpp, regamedll/dlls/bot/cs_bot_manager.cpp, regamedll/game_shared/bot/bot_util.h
Works as in CS:GO (http://wiki.multiplay.co.uk/CSGO/Bot_Commands)
Default value is "normal".
=> Added cvar bot_quota_mode

regamedll/dlls/multiplay_gamerules.cpp
Fixed as [here](https://github.com/s1lentq/ReGameDLL_CS/blob/7f45b101525c1f1454af09b2864d3cc2434031ee/regamedll/game_shared/voice_gamemgr.cpp#L170-L172)
=> Fix voice checks for spectators

regamedll/regamedll/regamedll_interfaces_impl.cpp
ReGamedll API: to allocate a string through engine.
=> Fix s1lentq/reapi/issues/53

regamedll/dlls/player.cpp
=> Break loop in OLD_CheckBuyZone, OLD_CheckBombTarget, OLD_CheckRescueZone

regamedll/dlls/player.cpp
=> Fix mp_forcerespawn (fix #111)

gradle.properties, regamedll/dlls/player.cpp, regamedll/dlls/player.h, regamedll/extra/cssdk/dlls/regamedll_api.h, regamedll/extra/cssdk/dlls/regamedll_interfaces.h, regamedll/public/regamedll/regamedll_api.h, regamedll/public/regamedll/regamedll_interfaces.h, regamedll/regamedll/regamedll_api_impl.cpp, regamedll/regamedll/regamedll_api_impl.h, regamedll/regamedll/regamedll_interfaces_impl.cpp
Thanks for additional help to @Adidasman1 and @s1lentq
=> ReGameDLL API: Implement API for StartDeathCam

regamedll/dlls/player.cpp
Bug demonstation: https://www.youtube.com/watch?v=oA5Y24WrkNY&ab_channel=wowz
=> Fix fall sound bug

regamedll/dlls/combat.cpp
=> Optimize PlayerBlind

regamedll/dlls/cbase.h, regamedll/dlls/player.cpp, regamedll/dlls/player.h, regamedll/extra/cssdk/dlls/cbase.h, regamedll/extra/cssdk/dlls/player.h, regamedll/extra/cssdk/dlls/regamedll_api.h, regamedll/public/regamedll/regamedll_api.h, regamedll/regamedll/regamedll_api_impl.h
- @s1lentq 
- Pavlik the Narcoman
- drugs
=> Fix mp_refill_bpammo_weapons not working on default weapons

regamedll/dlls/ggrenade.cpp, regamedll/dlls/weapons.cpp, regamedll/dlls/wpn_shared/wpn_c4.cpp
In a while I will add new bugfixes, but it's fine to merge now. And please don't squash commits I want to get better stats :trollface: 
- https://www.youtube.com/watch?v=RV-utOqHg_k - bug info
- https://forums.alliedmods.net/showthread.php?t=171831 - bug info
- https://t.me/devcs - some suggestions and bug reports
- @Vaqtincha - for suggestions
- Valve - stable buggy code
=> Fix some of C4 related bugs.

regamedll/dlls/wpn_shared/wpn_c4.cpp
issue reported here https://github.com/s1lentq/ReGameDLL_CS/issues/164
=> fix c4 bug

regamedll/game_shared/voice_gamemgr.cpp
If the value of sv_alltalk 2 or 3 the value of the variable bAllTalk should be False
=> Wrong checking CanPlayerHearPlayer

regamedll/dlls/ggrenade.cpp
This will allow to faster cancel progress bar on the defuser. As well as other stuff in `C4Think` will became more precise (like bomb exploding, detection of the defuse/plant in air and so on).
=> Make C4 more responsible

regamedll/dlls/client.cpp, regamedll/dlls/multiplay_gamerules.cpp, regamedll/dlls/observer.cpp, regamedll/dlls/player.cpp, regamedll/dlls/player.h
Thanks to @s008nyx for the information.
=> Fix spectator check, small refactoring

README.md
https://github.com/s1lentq/ReGameDLL_CS/blob/9374fced908d64d8dbc90c878605925b151078fa/regamedll/build.gradle#L135
https://software.intel.com/en-us/articles/c14-features-supported-by-intel-c-compiler
https://msdn.microsoft.com/en-us/library/hh567368.aspx
=> Update version requirement for VS and ICC

regamedll/dlls/ggrenade.cpp, regamedll/dlls/wpn_shared/wpn_c4.cpp
Thanks  to the great master of the ancient magic @s1lentq.
Related to dreamstalker/rehlds#555
=> Fix C4 dissapearance on inclined surfaces with Valve HLDS

regamedll/build.gradle, regamedll/common/mathlib.h, regamedll/dlls/animation.cpp, regamedll/dlls/player.cpp, regamedll/dlls/saverestore.cpp, regamedll/dlls/saverestore.h, regamedll/dlls/util.h, regamedll/engine/osconfig.h, regamedll/regamedll/hookchains_impl.cpp, regamedll/regamedll/hookchains_impl.h, regamedll/regamedll/precompiled.h, regamedll/regamedll/sse_mathfun.cpp, shared.gradle, shared_gcc.gradle, shared_icc.gradle
A working port to GCC 7.3. 
I also have added two new defines:
* HAVE_SSE enabled automatically when compiler is enabled SSE support. It will be used for updated ARM port of ReGameDLL_CS.
* NO_AMXX_HACKS disables ASM inline. It will be used for updated ARM port of ReGameDLL_CS.
=> GCC port and new defines for new ARM port

dist/game.cfg, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/player.cpp
Useful for servers with semiclip like KZ, Deathrun..ect
=> Add mp_kill_filled_spawn

regamedll/dlls/bot/cs_bot_vision.cpp, regamedll/dlls/game.cpp
req https://github.com/s1lentq/ReGameDLL_CS/issues/320
=> Bot vision update.

regamedll/dlls/weapons.h, regamedll/dlls/wpn_shared/wpn_ak47.cpp, regamedll/dlls/wpn_shared/wpn_aug.cpp, regamedll/dlls/wpn_shared/wpn_awp.cpp, regamedll/dlls/wpn_shared/wpn_deagle.cpp, regamedll/dlls/wpn_shared/wpn_elite.cpp, regamedll/dlls/wpn_shared/wpn_famas.cpp, regamedll/dlls/wpn_shared/wpn_fiveseven.cpp, regamedll/dlls/wpn_shared/wpn_g3sg1.cpp, regamedll/dlls/wpn_shared/wpn_galil.cpp, regamedll/dlls/wpn_shared/wpn_glock18.cpp, regamedll/dlls/wpn_shared/wpn_m249.cpp, regamedll/dlls/wpn_shared/wpn_m4a1.cpp, regamedll/dlls/wpn_shared/wpn_mac10.cpp, regamedll/dlls/wpn_shared/wpn_mp5navy.cpp, regamedll/dlls/wpn_shared/wpn_p228.cpp, regamedll/dlls/wpn_shared/wpn_p90.cpp, regamedll/dlls/wpn_shared/wpn_scout.cpp, regamedll/dlls/wpn_shared/wpn_sg550.cpp, regamedll/dlls/wpn_shared/wpn_sg552.cpp, regamedll/dlls/wpn_shared/wpn_tmp.cpp, regamedll/dlls/wpn_shared/wpn_ump45.cpp, regamedll/dlls/wpn_shared/wpn_usp.cpp, regamedll/public/regamedll/API/CSPlayerWeapon.h
Creating m_flBaseDamage member that change basic damage of weapons deals before any multiplier, such as hitgroup, armor, distance and bullet penetration.
=> Add m_flBaseDamage member

regamedll/dlls/player.cpp
Hello, just a little addition as @LevShisterov suggested to fix issue https://github.com/s1lentq/ReGameDLL_CS/issues/238
=> Fix for dead player inclination

regamedll/dlls/util.cpp
A small fix for some UTIL functions that helps prevent shellcode injection using BSP files.
=> Buffer overflow fix

regamedll/dlls/func_break.cpp
More info in #347, i've broken that pr @_@
=> Fix player's velocity on pushable use

regamedll/dlls/game.cpp
=> Radio enchance cvars

regamedll/dlls/multiplay_gamerules.cpp
=> Fix VIP mechanic

regamedll/dlls/ggrenade.cpp
While you are defusing you can unpress E and a friend can continue to defuse for you
=> Fix c4 defuse glitch

regamedll/common/const.h, regamedll/dlls/client.cpp
The analog of FM_CheckVisibility with "return 1"
=> Add force visibility effect

regamedll/dlls/player.cpp
for more info visit this thread : https://forums.alliedmods.net/showthread.php?t=317763
=> Disconnected players func_tank fix

README.md, dist/game.cfg, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/ggrenade.cpp, regamedll/dlls/player.cpp
Condition-Zero style scenario icon near round timer.
=> Add CVar mp_show_scenarioicon

regamedll/dlls/client.cpp
More info https://goldsrc.ru/threads/3430/ 
ps: WARNING! Russian Language! It can be dangerous! (hi Arkshine xD)
=> Autobuy/Rebuy Fixes

regamedll/dlls/items.cpp, regamedll/dlls/weapons.cpp
More info:
https://github.com/s1lentq/ReGameDLL_CS/issues/423
https://github.com/ValveSoftware/halflife/issues/2175
=> Armor pickup fix

regamedll/dlls/player.cpp
Transferred the condition, to avoid unnecessary checks.
=> Ignorerad command small optimization

regamedll/dlls/sound.cpp, regamedll/dlls/util.cpp, regamedll/dlls/wpn_shared/wpn_knife.cpp
=> Fix hitsounds on vehicles

gradle.properties, regamedll/dlls/API/CSPlayer.cpp, regamedll/dlls/client.cpp, regamedll/dlls/weapons.cpp, regamedll/public/regamedll/API/CSPlayer.h, regamedll/public/regamedll/regamedll_api.h
Allow to override m_bCanShoot, for example able to fire at freeze time
=> Add m_bCanShootOverride member

regamedll/dlls/API/CSPlayer.cpp, regamedll/dlls/player.cpp, regamedll/public/regamedll/API/CSPlayer.h
Able to set custom respawn time for m_flRespawnPending without mp_forcerespawn enabled
=> Remove respawn dependency on forcerespawn cvar

regamedll/game_shared/bot/bot.h
bug https://github.com/dreamstalker/rehlds/blob/master/rehlds/engine/pr_cmds.cpp#L1943 ?
=> Reset entvars on create bot

regamedll/dlls/API/CAPI_Impl.cpp, regamedll/dlls/API/CAPI_Impl.h, regamedll/dlls/cbase.cpp, regamedll/dlls/cbase.h, regamedll/dlls/func_tank.cpp, regamedll/dlls/wpn_shared/wpn_elite.cpp, regamedll/dlls/wpn_shared/wpn_m3.cpp, regamedll/dlls/wpn_shared/wpn_xm1014.cpp, regamedll/public/regamedll/regamedll_api.h, regamedll/regamedll/hookchains_impl.h
@s1lentq:
Please control (because GitHub is not my "thing", and I am not able to test & compile such stuff) & merge those new useful hooks to your project.
I basically grabbed it from another PR who got removed by its author (for "charabia" reason!).
PS # 1: The latest file modified (hookchains_impl.h) does not seem necessary (or I do not see it at the moment), so feel free to do not merge it.
PS # 2: Not so complicated to be eloquent & add an informative title! Hehehehehe!
=> API: Add "CBaseEntity::Fire<Bullets[3]|Buckshots>" hooks.

regamedll/dlls/player.cpp, regamedll/dlls/unisignals.h
=> Reset client m_signals on fullupdate

regamedll/dlls/wpn_shared/wpn_sg550.cpp, regamedll/msvc/ReGameDLL.vcxproj
bug https://youtu.be/PYq1BRg_fbo
=> fix weapon_sg550

regamedll/dlls/util.cpp
add check g_engfuncs.pfnEngCheckParm is nullptr or not.
=> fix crash in UTIL_AreHostagesImprov

regamedll/dlls/client.cpp, regamedll/dlls/multiplay_gamerules.cpp, regamedll/dlls/weapons.cpp, regamedll/dlls/weapons.h, regamedll/dlls/wpn_shared/wpn_famas.cpp, regamedll/dlls/wpn_shared/wpn_galil.cpp, regamedll/dlls/wpn_shared/wpn_m3.cpp, regamedll/dlls/wpn_shared/wpn_xm1014.cpp
Implement weapon flag ITEM_FLAG_NOFIREUNDERWATER to allow user to changes behavior firing underwater
=> Add weapon flag ITEM_FLAG_NOFIREUNDERWATER

regamedll/dlls/triggers.cpp, regamedll/dlls/triggers.h, regamedll/extra/Toolkit/GameDefinitionFile/regamedll-cs.fgd
Same as `mp_legacy_bombtarget_touch 0/1` (for level desingners)
=> func_bomb_target: new feature "strict touch"

README.md, dist/game.cfg, regamedll/dlls/client.cpp, regamedll/dlls/game.cpp, regamedll/dlls/game.h
=> Add new CVar `sv_allchat`

regamedll/dlls/items.cpp
fix https://github.com/s1lentq/ReGameDLL_CS/issues/769
=> fix: update scoreboard attributes on defuser pickup

README.md, regamedll/dlls/game.cpp
Related to: https://github.com/s1lentq/ReGameDLL_CS/issues/728
=> Add an argument to `swapteams` command

regamedll/dlls/multiplay_gamerules.cpp, regamedll/dlls/util.cpp
https://github.com/ValveSoftware/halflife/issues/2190
=> Implement `game_round_start` & `game_entity_restart` triggers

regamedll/dlls/player.cpp, regamedll/dlls/weapons.cpp
=> Weaponbox ammopack hardcode

regamedll/dlls/ggrenade.cpp
fix https://github.com/s1lentq/ReGameDLL_CS/issues/874
=> SG_Detonate: make event realible

regamedll/dlls/bot/cs_bot_manager.cpp
=> Fix bot_kill command

regamedll/dlls/weapons.cpp
-title-
Related to #992 
References: https://forums.alliedmods.net/showthread.php?p=1620401
=> Fix Shotguns reload flag not getting reset on weapon changing

README.md, dist/game.cfg, regamedll/dlls/client.cpp, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/gamerules.h
Added `mp_vote_flags` and `mp_votemap_min_time` cvars to handle voting systems in server, you can check README.md to see more information or related modified code.
=> Added `mp_vote_flags` and `mp_votemap_min_time` cvars

regamedll/dlls/wpn_shared/wpn_deagle.cpp
https://github.com/s1lentq/ReGameDLL_CS/issues/927
=> Fix Deagle Anim

README.md
=> add desc to readme

regamedll/dlls/player.cpp
Fix mistake in UpdateLocation (its calculated a lot due to wrong condition)
=> fix: calculate UpdateLocation fun not so often

regamedll/dlls/player.cpp, regamedll/dlls/player.h
Just a little dumb code cleanup
=> Group m_pTank detachment logic

dist/game.cfg
Adds weapons affected by mp_knockback cvar.
=> Add weapons info to mp_knockback
