regamedll/dlls/player.cpp
It used to check if m_pActiveItem was != 0 after referencing it the line before.
(Fucked up last PR)
=> Fix player.cpp crash when m_pActiveItem = null

regamedll/dlls/bot/cs_bot_manager.cpp
Fixes incorrectly terminated string caused by appending backslash.
=> Fix crash on bot_nav_save

regamedll/dlls/animation.cpp, regamedll/dlls/player.cpp
This fixes crash, in case ReGameDLL_CS running with a local client. 
If local client do a tracing for studio models, it calls SV_StudioSetuoBones with a NULL pEdict. So it must be checked before we call GetPlayerYaw/Pitch to prevent crash.
=> Fix crash when custom SV_StudioSetupBones exported to the engine

regamedll/pm_shared/pm_shared.cpp
Referring to HLSDK, pm_shared compiles with server and client both, so I added client specific variables and it don't errors when compiling it with CLIENT_DLL macro enabled.
=> Add client specific variables

regamedll/dlls/player.cpp, regamedll/dlls/triggers.cpp
currently when you set mp_buytime 0 it shows buyicon and its allows you to open weapons menu and when you try buy somthing it show "0 seconds passed since..." now with this patch no icon will be shown and menu will not open.
=> completly disable buyzone when mp_buytime is 0

README.md, dist/game.cfg
Source code says to use "mp_round_restart_delay" FCVAR but it in the doc it was inverted to "mp_restart_round_delay" so just replaced and fixed it.
=> Round restart delay.

regamedll/dlls/player.cpp
Hard coded (0, 0,+32) cause spray bugs. More info: https://forums.alliedmods.net/showpost.php?p=1660912&postcount=9
Thanks to @Arkshine for proposed fix
=> Fix CSprayCan position relative to player

regamedll/dlls/player.cpp
Return immediately, when we found something, instead of calling `UTIL_FindEntityByClassname` 2 times.
=> Optimize CBasePlayer::SendWeatherInfo

regamedll/dlls/client.cpp
Motivated by https://github.com/ValveSoftware/halflife/pull/1717.
This also fixes a bug with roof boost glitch (idk how to name it properly, I found it [here](https://forums.alliedmods.net/showthread.php?t=81877)). Video with demonstration https://youtu.be/9zkamv8shqM?t=7m55s from [here](https://forums.alliedmods.net/showthread.php?t=287955).
There is also [info](https://gist.github.com/WPMGPRoSToTeMa/2e6e0454654f9e4ca22ee3e987051b57) about `HUD_GetHullBounds` patching for the client. (this fixes twitching when you staying above crouching player https://youtu.be/0BUMoGDitVU)
=> Fixed GetHullBounds

regamedll/dlls/player.cpp
Originally reported [here](https://github.com/ValveSoftware/halflife/issues/1815).
This bug is not reproducable in CS by default. To reproduce it you can enable knife drop, then use this command sequence `drop weapon_knife;drop;lastinv`.
=> Fixed bug with lastinv (fix from 7561)

README.md, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/player.cpp
https://youtu.be/qx1A4HDzhPA
I <3 Valve.
Thanks to @wopox1337 for idea
=> Add cvar for radio icon

regamedll/dlls/ggrenade.cpp
I wasn't able to reproduce bugs  5 and 6 in #185, but I guess it's possible, so better to cancel progress bar when defuser dies.
=> Fix dead defuser progress bar issues

regamedll/dlls/client.cpp
kevlar.wav is empty sound, but I guess this should be fine
Credits: @Vaqtincha for bug report (24 in #185)
=> Prevent kevlar.wav from overwriting gunpickup2.wav sound

regamedll/dlls/multiplay_gamerules.cpp
This should make `CCStrikeGameMgrHelper::CanPlayerHearpPlayer` code easier to understand.
=> Refactor CanPlayerHearPlayer

regamedll/dlls/ggrenade.cpp
This should make it safer to defuse in low framerate, but make defuse check 2 time more responsible
=> Increase NEXT_DEFUSE_TIME.

regamedll/dlls/wpn_shared/wpn_c4.cpp
It is actually related to CS 1.3 training room: https://www.youtube.com/watch?v=cqGrnXFX8Vk
=> Remove useless code from CC4::Use

README.md, dist/game.cfg, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/triggers.cpp, regamedll/dlls/triggers.h
Thanks to @s1lentq and @wopox1337  
Cvar demo: https://youtu.be/h4_-9lVCoKk
https://youtu.be/O_IF3UhxqXg (0:25 shows you bug)
=> Add mp_legacy_bombtarget_touch cvar

regamedll/dlls/wpn_shared/wpn_c4.cpp
Since `cl_righthand 1` is the most popular option we must adjust ourselves for it (look for the wires after the bomb is planted).
=> Adjust bomb angles for righthanded users (resolves #218)

README.md, regamedll/dlls/multiplay_gamerules.cpp
Why?
BUG: When user set mp_fraglimit < 0 - server will reboot every map when server have players.
=> Fix bug, mp_fraglimit is less than zero

regamedll/dlls/client.cpp, regamedll/dlls/multiplay_gamerules.cpp
Game dll considers third party bots as humans when dealing with humans_join_team cvar, thus making those bots to join team specified in this cvar.
=> Do not ignore thirdparty bots in humans_join_team cvar checks.

regamedll/dlls/player.cpp
Spectator watching player did not see radio cmd that player sent.
=> Fix bug with radio commands

regamedll/dlls/util.cpp
Probably may resolve https://github.com/dreamstalker/rehlds/issues/754.
=> Fix buffer overrun in `UTIL_dtosX` functions

regamedll/dlls/func_tank.cpp, regamedll/dlls/player.cpp
You have only one AWP weapon (without knife) If you drop a weapon with zoom, then the player does not reset speed and zoom.
=> Player reset zoom & speed.

regamedll/dlls/hintmessage.cpp, regamedll/dlls/player.cpp, regamedll/public/utlvector.h
Discovered when running under AddressSanitizer.
```
Direct leak of 94992 byte(s) in 271 object(s) allocated from:
#0 0xf79e74bb in __interceptor_malloc (/usr/lib/gcc/i686-linux-gnu/10/libasan.so+0xac4bb)
#1 0xeca1553b in CUtlMemory<CHintMessage*, int>::Grow(int) /home/j4/github/ReGameDLL_CS/regamedll/public/utlmemory.h:294
#2 0xeca1553b in CUtlVector<CHintMessage*>::GrowVector(int) /home/j4/github/ReGameDLL_CS/regamedll/public/utlvector.h:260
#3 0xeca1553b in CUtlVector<CHintMessage*>::InsertBefore(int, CHintMessage* const&) /home/j4/github/ReGameDLL_CS/regamedll/public/utlvector.h:364
#4 0xeca1553b in CUtlVector<CHintMessage*>::AddToTail(CHintMessage* const&) /home/j4/github/ReGameDLL_CS/regamedll/public/utlvector.h:349
#5 0xeca1553b in CHintMessageQueue::AddMessage(char const*, float, …
```
=> Fixed memory leak with hintmessage.

regamedll/dlls/hintmessage.cpp, regamedll/dlls/hintmessage.h
When using ReAPI native rg_hint_message it won't work correctly because it tries to access to a pointer which does not exists in CHintMessage::Send.
=> Fix compatibility whit rg_hint_message

regamedll/dlls/multiplay_gamerules.cpp
Setting _cl_autowepswitch to 2 will now enable auto weapon switching on pickup of a better weapon except when holding Primary or Seconday attack
=> Add newest feature of _cl_autowepswitch

dep/cppunitlite/msvc/cppunitlite.vcxproj, regamedll/dlls/maprules.cpp, regamedll/dlls/maprules.h, regamedll/dlls/player.cpp, regamedll/extra/Toolkit/GameDefinitionFile/regamedll-cs.fgd, regamedll/msvc/ReGameDLL.vcxproj
game_player_equip: check UsuOnly flag
fix VS2015 compile
=> game_player_equip fixes/enhancement

regamedll/dlls/player.cpp, regamedll/dlls/player.h, regamedll/extra/Toolkit/GameDefinitionFile/regamedll-cs.fgd
Test map attached
[test.zip](https://github.com/s1lentq/ReGameDLL_CS/files/6562204/test.zip)
=> enhance "player_weaponstrip" entity

regamedll/extra/Toolkit/GameDefinitionFile/regamedll-cs.fgd
Добавлены пропавшие spawnflags 64 и 128 у func_rot_button, которые определяют вращение по конкретной оси(стандарт Z).
=> regamedll-cs.fgd

regamedll/dlls/observer.cpp
=> Allow observe for dying player with EF_NODRAW effect

README.md, dist/game.cfg, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/player.cpp
Resolves #560 
- Implement the free_armor logic.
- Update game.cfg with `mp_free_armor` command
- Update readme with `mp_free_armor` command
- Register `mp_free_armor` cvar
```cpp
// Give the player free armor on player spawn
// 0 - No armor (default behavior)
// 1 - Give Kevlar
// 2 - Give Kevlar and Helmet
//
// Default value: "0"
mp_free_armor 0
```
=> Add new CVar `mp_free_armor`

regamedll/dlls/API/CAPI_Impl.cpp, regamedll/dlls/API/CAPI_Impl.h, regamedll/dlls/player.cpp, regamedll/dlls/player.h, regamedll/public/regamedll/regamedll_api.h, regamedll/version/version.h
```cpp
CBasePlayer::Pain(int iLastHitGroup, bool bHasArmour);
CBasePlayer::DeathSound();
CBasePlayer::JoiningThink();
```
=> Implement new player hooks

regamedll/dlls/API/CAPI_Impl.cpp, regamedll/dlls/API/CAPI_Impl.h, regamedll/dlls/observer.cpp, regamedll/dlls/player.h, regamedll/public/regamedll/regamedll_api.h
related issue s1lentq/reapi#207
=> Implement `CBasePlayer::Observer_SetMode` hook

regamedll/dlls/API/CAPI_Impl.cpp, regamedll/dlls/API/CAPI_Impl.h, regamedll/dlls/observer.cpp, regamedll/dlls/player.h, regamedll/public/regamedll/regamedll_api.h
The game have a bug when you are specting in first person, quickly changing players it is possible to "bug" the game and see through walls for a fraction of a second. This hook is needed to try to fix this bug.
=> Implement `CBasePlayer::Observer_FindNextPlayer()` hook

regamedll/dlls/API/CAPI_Impl.cpp, regamedll/public/regamedll/regamedll_api.h
related https://github.com/s1lentq/reapi/pull/200
=> Implement `CGib::SpawnHeadGib` and `CGib::SpawnRandomGibs`

regamedll/msvc/ReGameDLL.vcxproj
Thread local storage (TLS) in shared libraries loaded by LoadLibrary() is not completely supported on Windows XP / Server 2003, causing game to crash if run on this platforms. But ReGamedDLL uses v140_xp platform toolset with GitHub Actions when building windows binary, assuming that XP/2003 must be supported.
This only affects VS2015+ builds, so we're not checking v120_xp toolset.
Probably the same should be applied for ReHLDS to support Windows XP properly.
=> Disable thread-safe initialization for static local variables

regamedll/dlls/weapons.h, regamedll/dlls/wpn_shared/wpn_ak47.cpp, regamedll/dlls/wpn_shared/wpn_aug.cpp, regamedll/dlls/wpn_shared/wpn_famas.cpp, regamedll/dlls/wpn_shared/wpn_galil.cpp, regamedll/dlls/wpn_shared/wpn_m249.cpp, regamedll/dlls/wpn_shared/wpn_m4a1.cpp, regamedll/dlls/wpn_shared/wpn_mac10.cpp, regamedll/dlls/wpn_shared/wpn_mp5navy.cpp, regamedll/dlls/wpn_shared/wpn_p90.cpp, regamedll/dlls/wpn_shared/wpn_sg552.cpp, regamedll/dlls/wpn_shared/wpn_tmp.cpp, regamedll/dlls/wpn_shared/wpn_ump45.cpp
Fixes and improves smooth spread transitions when shooting automatic weapons.
🤌
=> Fix `m_flAccuracy` calculation

regamedll/dlls/player.cpp
related https://github.com/s1lentq/ReGameDLL_CS/pull/584
=> Reset `m_flNextFollowTime` before trying to find next target after previous target death

regamedll/dlls/player.cpp
hide observer crosshair if we cancel `HIDEHUD_CROSSHAIR`.
fix #671
=> fix observer crosshair bug

README.md
About this:
https://github.com/s1lentq/ReGameDLL_CS/blob/c002edd5b18a8408e299bc6cccfec2c7de56ba3d/regamedll/dlls/player.cpp#L6527-L6544
=> README.md: Note about `impulse 255` command

regamedll/dlls/wpn_shared/wpn_g3sg1.cpp
Changing does not touch reload time (only visual animation time changes)
ps:
G3SG1 too powerful weapon. What do you think can developers wanted to make a reload time 4.7s and not 3.5s
demo
https://youtu.be/IuOZkmebRbE
=> g3sg1 animation duration fix

regamedll/dlls/triggers.cpp, regamedll/extra/Toolkit/GameDefinitionFile/regamedll-cs.fgd
Explained here: https://github.com/fireblizzard/agmod/pull/11#issuecomment-1073151032
=> Added spawnflags for keep player angles & velocity in trigger_teleport

README.md, dist/game.cfg, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/ggrenade.cpp
```cpp
// How many bonuses (frags) will get the player who defused or exploded the bomb.
// 3 - (default behaviour)
//
// Default value: "3"
mp_give_c4_frags 3
```
=> New CVar: `mp_give_c4_frags`

README.md, dist/game.cfg, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/multiplay_gamerules.cpp
https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/multiplay_gamerules.cpp#L1471
This business logic does not work correctly because the code below does not consider by 50%.
https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/multiplay_gamerules.cpp#L1482
Adding cvar for ratio and and default value for compatibility.
=> New CVar: `mp_hostages_rescued_ratio`

regamedll/dlls/wpn_shared/wpn_aug.cpp, regamedll/dlls/wpn_shared/wpn_sg552.cpp
Bug is caused because of not checking weapon's FOV in some conditions.
close https://github.com/s1lentq/ReGameDLL_CS/issues/703
comment from @wopox1337 
> If we keep changing the shared code of weapons for the server side, at some point in time we will get more and more out of sync with the client side (prediction) and this will adversely affect the overall experience of the game for the average player.
> 
> I propose to leave this behavior "as is".
Well, if you don't want to merge it. Let be open to documentation.
=> Fix: 'fast fire glitch' at AUG/SG552

.github/workflows/build.yml
This way it will take less time to build a project caused by Pull requests.
Building with `ICC` is left for releases only.
=> CI: Keep the `ICC` build for releases only

regamedll/common/const.h, regamedll/dlls/cbase.cpp, regamedll/dlls/combat.cpp
This will allow distinguishing different trace types easily, For example an efficient method to make bullets penetrate through teammates would be: 
```
#include <amxmodx>
#include <fakemeta>
#include <reapi>
// Custom flags that we can retrieve in pfnShouldCollide
// Starting from BIT(16) to reserve space for more flags for Engine
#define FTRACE_BULLET				(1<<16)
#define FTRACE_FLASH				(1<<17)
public plugin_init() {
register_plugin("Bullets penetrate teammates", "0.0.1", "JustGo")
register_forward(FM_ShouldCollide, "FMHook_ShouldCollide")
register_forward(FM_AddToFullPack, "FMHook_AddToFullPack_Post", 1)
}
public FMHook_ShouldCollide(entTouched, entOther) {
if(!is_user_alive(entTouched) || !is_user_alive(entOther)) return FMRES_IGNORED
if((global_get(glb_trace_flags) & FTRACE_BULLET) && …
```
=> Add new trace flags

regamedll/dlls/weapons.cpp
* fix bug when picking weaponbox grenades with ammo > 1
If the player had one grenade and the weaponbox has 2 and when the player picks up one, the weaponbox disappears. 
although it should stay with one grenade
* fix bug pickup sound (if the player has ammo > 0)
demo
https://youtu.be/k-ckR6FDJVQ
=> Grenade weaponbox ammo pickup fix

regamedll/game_shared/bot/bot_util.cpp
Related to #761
It just disables BotPrecache on vanilla CS 1.6, and limited only to CZero or CS 1.6 with improved Bots. You can free a few sounds from precache list.
=> Disable BotPrecache whether game is CS 1.6

regamedll/dlls/weapons.h, regamedll/dlls/wpn_shared/wpn_knife.cpp
*title*
Feature addition, plus a few line changes, up to modders preferences.
=> Make Knife back stab multiplier customizable

regamedll/dlls/career_tasks.cpp, regamedll/dlls/player.cpp
Related to #835 
1. Code cleaning on `CBasePlayer::Killed` which inside calls `HandleEnemyKill` with wrong parameter order
2. Changed conditions inside `CCareerTask::OnEvent` on hostage-related events which detects leader/follower with the unused `m_target` member and changed with `IsFollowing` method.
=> `CZero`: Fix broken Career Tasks

regamedll/dlls/effects.cpp, regamedll/dlls/player.cpp, regamedll/dlls/util.cpp, regamedll/dlls/util.h, regamedll/dlls/weapons.cpp
Same argument as #830 : variables used as parameters, mostly used in a old fashioned programming way and on singleplayer hlsdk branch.
Might be useless but opens mind about certain code that should be reviewed in detail.
=> Little code cleaning: g_vecAttackDir

regamedll/dlls/gib.cpp
Adding a boundary to this magic number in (rare) cases where sv_maxvelocity < 1500, to avoid velocity bug and console messages.
=> Adjust gib's velocity limit according to sv_maxvelocity

regamedll/dlls/API/CSPlayer.cpp, regamedll/dlls/animating.cpp, regamedll/dlls/animation.cpp, regamedll/dlls/animation.h, regamedll/dlls/cbase.h, regamedll/dlls/client.cpp, regamedll/dlls/combat.cpp, regamedll/dlls/multiplay_gamerules.cpp, regamedll/dlls/observer.cpp, regamedll/dlls/observer.h, regamedll/dlls/player.cpp, regamedll/dlls/player.h
=> `mp_fadetoblack` fade timings now depends from `mp_dying_time` CVar

regamedll/pm_shared/pm_shared.cpp, regamedll/public/regamedll/API/CSPlayer.h
- Added 4 members to CSPlayer class:
- `m_flJumpHeight`: player vertical jump force, 0 = default (~268.3)
- `m_flLongJumpHeight`: player vertical jump force with longjump enabled, 0 = default (~299.3)
- `m_flLongJumpForce`: player horizontal jump force with longjump enabled, 0 = default (560.0)
- `m_flDuckSpeedMultiplier`: player duck speed multiplier, 0 = default (0.3333)
- Cached pmove player's CSPlayer pointer in a global variable
=> `API`: CSPlayer new members (physics related)

regamedll/dlls/player.cpp
`m_pDriver` is a member present only on `CFuncVehicle` class, in `CBasePlayer` workflow there's a train quitting logic where game is setting `m_pDriver` to `NULL` on both entities **func_vehicle** and **func_tracktrain**, which shares `FCAP_DIRECTIONAL_USE` ObjectCaps flag but the last one doesn't have m_pDriver member (including the implicit cast to CFuncVehicle on code)
Workaround (and ToDo): Train quitting logic is quite similar, should that be grouped in a single function?
=> Ensure m_pDriver assignation on func_vehicle only

regamedll/dlls/API/CSPlayer.cpp, regamedll/dlls/client.cpp, regamedll/dlls/player.cpp, regamedll/dlls/player.h
- Fixed `item_thighpack` entity not spawning on `CBasePlayer::Disappear` (which shares logic with `CBasePlayer::Killed`). Fixed version deleted `GiveNamedItem` (reasonably) but nobody coded the entity spawning.
- Fixed `CCSPlayer::RemovePlayerItemEx` not clearing ProgressBar HUD when removing defuser.
- Ensuring m_bIsDefusing assignation whenever defuser is removed from player.
- Defuser removal logic grouped into `CBasePlayer::RemoveDefuser`.
- Some minor logic changes and unneeded code erase.
=> Various defuser fixes and code refactory

regamedll/dlls/bot/cs_bot.h, regamedll/dlls/bot/cs_bot_learn.cpp
The iterator `m_analyzeIter` could potentially become invalid due to the possibility of `TheNavAreaList` removing elements while the analysis is ongoing.
It's recommended to test the proposed fix thoroughly before merging it
=> Fixed crash sometimes occurring while map analyzing for zbot navigation

regamedll/dlls/player.cpp
This fix addresses an issue with the inaccurate recording of the last damage (m_lastDamageAmount) due to incorrect sequencing of operations in the code. In the original code, damage was recorded before it was adjusted based on armor, potentially resulting in the storage of incorrect data. This bug could affect precise damage calculations and gameplay analysis, particularly when tracking and assessing damage over time.
=> Fixed of m_lastDamageAmount  recording during armor calculation

regamedll/dlls/weapons.cpp
How to reproduce:
- Test environment cvars:
- mp_buytime -1
- mp_startmoney 10000
- mp_forcerespawn 1
- mp_ct_give_default_knife 0
- mp_t_give_default_knife 0
- mp_nadedrops 1
- Join CT, buy hegrenade from buymenu and then change team to T
- You'll drop your hegrenade cause of death, and respawn in a few seconds
- Having no guns (ensure you have none), you'll pickup that hegrenade and see you are not deploying it until you force it (pressing 4, or typing weapon_hegrenade in console) - may lead in a HUD bug in some cases
This commit fixes two issues:
- Grenade weaponbox not deploying on unarmed player after being picked up from ground.
- HEGrenade not being deployed when picked up from ground if you are holding a Flashbang, considering HEGrenade has more weight than Flashbang.
This issue …
=> Fix: Grenade weaponbox not deploying on unarmed player

README.md, dist/game.cfg, regamedll/dlls/combat.cpp, regamedll/dlls/game.cpp, regamedll/dlls/game.h
Related to https://github.com/s1lentq/ReGameDLL_CS/issues/572
Instead of a "No Team Flash" idea, this command alters the Flashbang's performance.
You can flash your teammates, flash yourself only or neither two cases.
This also affects on `mp_freeforall` as the players on your team are now enemies.
=> New CVar: `mp_team_flash`

regamedll/dlls/API/CSPlayer.cpp, regamedll/dlls/player.cpp, regamedll/dlls/weapons.cpp, regamedll/dlls/weapons.h
Extension of the DestroyItem method for the CBasePlayerItem class
- Added a boolean value to indicate the success of item deletion
- Implemented a condition for handling WEAPON_C4 specifically
- Added a condition to check for the presence of primary weapons
Updated the item removal mechanism in the RemovePlayerItemEx method
- Fixed a double hook invocation issue for grenades and performed minor code refactoring
Fix duplicate remove of item_thighpack
=> Refactored RemovePlayerItemEx and Extended DestroyItem in CBasePlayerItem

regamedll/dlls/API/CSPlayer.cpp, regamedll/public/regamedll/API/CSPlayer.h
- Added C4 drop when changing from CT/T to SPEC
- Deleted `m_bHasC4` assignation to false due to code redundancy in `RemoveAllItems`
- Changed return types of `DropShield` and `DropPlayerItem` to `CBaseEntity` to retrieve created entity index.
This requieres to update API version and submodules like ReAPI. (actually done)
EDIT: this partially grabs #699 changes in a segmented/detailed way
=> `API`: CSPlayer methods enhancement

regamedll/dlls/client.cpp, regamedll/dlls/weapontype.cpp, regamedll/dlls/weapontype.h
Sort of an old bug. If client prediction is activated (`cl_lw 1`), player is holding a weapon whose maxclip was altered (easily nowadays with `rg_set_iteminfo` natives), active weapon's clip is equal to altered maxclip, and then presses the reload button, it will reproduce a client-side reload animation which stops until player releases the button, because client thinks you met the conditions to reload the weapon considering its clip differs from its maxclip.
This fixes that weapon animation by faking the weapon's current clip in case the weapon has a different maxclip from its original, and is actually holding the gun with `clip == newmaxclip`.
You can see the conditions in the files changed.
I might say it needs tests 👍
=> `FIX`: Reloading animation bug while holding weapon with altered Maxclip

README.md, dist/game.cfg, regamedll/dlls/API/CAPI_Impl.cpp, regamedll/dlls/API/CAPI_Impl.h, regamedll/dlls/API/CSPlayer.cpp, regamedll/dlls/cbase.cpp, regamedll/dlls/cbase.h, regamedll/dlls/client.cpp, regamedll/dlls/combat.cpp, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/gamerules.h, regamedll/dlls/multiplay_gamerules.cpp, regamedll/dlls/player.cpp, regamedll/dlls/player.h, regamedll/dlls/weapons.cpp, regamedll/msvc/ReGameDLL.vcxproj, regamedll/msvc/ReGameDLL.vcxproj.filters, regamedll/public/regamedll/API/CSEntity.h, regamedll/public/regamedll/API/CSPlayer.h, regamedll/public/regamedll/regamedll_api.h, regamedll/public/utlarray.h
**Description**
These changes introduces enhancements to the DeathNotice function,
providing extra death flags to convey more information in death messages.
These flags are used to include extra details about player deaths, making death messages more informative
- Extra Death Flags:
- PLAYERDEATH_POSITION (Bit 1):
Position of Victim's Death: This flag includes the coordinates (X, Y, Z) of the place where the victim died.
It is useful for displaying a 'dead icon' on the HUD radar, indicating the victim's death location.
- PLAYERDEATH_ASSISTANT (Bit 2):
Index of Assistant: When set, this flag includes the index of the assisting player who helped the attacker kill the victim. It allows players to know who assisted in the kill.
- PLAYERDEATH_KILLRARITY (Bit 4):
Kill Rarity Classification: …
=> Add an extended player's DeathMsg message

regamedll/dlls/client.cpp, regamedll/dlls/items.cpp, regamedll/dlls/player.cpp, regamedll/dlls/player.h
- Group defuser addition behaviour into a single function
- Force SetScoreboardAttrib function correctly (not present in original binary, in both ways obtainable)
NOTE: this changes the order of a few messages sent to client while obtaining this item
=> Small defuser refactory

regamedll/dlls/observer.cpp
This isn't coded in the original binary. `Observer_IsValidPlayer `meets conditions in a statement inside `Observer_SetMode `with a few differences. This PR just calls this function instead which wont behave different and allows modders a better handling of target choosing.
=> Observer_SetMode: Use Observer_IsValidPlayer function inside

regamedll/dlls/player.cpp
- Ensuring m_bHasPrimary member assignation when dropping a primary weapon, you can have more than 1 weapon (in modded scenarios) and you can grab a shield by just dropping one weapon.
- Ensuring m_bHasPrimary member assignation every time a weaponbox entity is successfully created (in modified scenarios)
=> DropPlayerItem: Ensure HasPrimary flag assignation on successful weapon removal

regamedll/dlls/multiplay_gamerules.cpp
In original CS behaviour it was expected to drop a defuser when a player disconnects if carrying. This enables that feature by creating an `item_thighpack` entity on the position of the disconnected player.
ToDo: discuss the fact of adding a cvar to enable/disable this new change that can alter game behaviour in "competitive" scenarios.
=> Unreleased content: Drop defuser on disconnect

regamedll/dlls/player.cpp
This issue pertains to an inaccurate display of player info when playback recorded demo file.
During demo playback, essential data such as player team, frags, deaths, and related info are missing when the demo is initially started.
Consequently, all players are displayed on the scoreboard as "SPECTATOR" with 0 frags and 0 deaths etc and until when new in-game events occur, but it takes time.
The proposed fix involves enhancing the `CBasePlayer::ForceClientDllUpdate` function
Including updating more data related to:
- `TeamInfo`  player team
- `ScoreInfo` frags and deaths info
- `Radar` player positions on the radar
- `ScoreAttrib` player attributes (e.g., DEAD, BOMB, VIP)
- `Location` player locations
=> Added updating more game info to the player who started recording the demo

README.md, dist/game.cfg, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/pm_shared/pm_shared.cpp
- Added cvar `mp_freezetime_duck` which allow ducking during freezetime.
`(0)` disabled
`(1)` enabled (default behaviour)
- Added cvar `mp_freezetime_jump` which allow jumping during freezetime. 
`(0)` disabled
`(1)` enabled (default behaviour)
Tested, work as intended 😄 
PS: Cvar's names/description corrections are welcome
=> New CVars: `mp_freezetime_duck` and `mp_freezetime_jump` 

regamedll/dlls/basemonster.cpp, regamedll/dlls/cbase.cpp, regamedll/dlls/cbase.h, regamedll/dlls/player.cpp, regamedll/dlls/player.h, regamedll/public/regamedll/API/CSEntity.h
- Use `m_pevLastInflictor` member from `CSEntity` class to hold entity's last inflictor set in `CBaseMonster::TakeDamage`, instead of a global variable. This will allow inflictor modification/retrieval inside `Killed` function.
- Add inflictor assignation also on `CBaseEntity::TakeDamage` for custom entities.
=> Use CSEntity member to hold last inflictor from TakeDamage

regamedll/dlls/cbase.cpp, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/ggrenade.cpp, regamedll/dlls/gib.cpp
Issue #887 
Added cvar pointer caching of sv_maxvelocity. Did a little research on engine and haven't found more hardcoded usages of 2000 units.
=> Fixed grenades disappearing when speed exceeds 2000 fixed units ignoring sv_maxvelocity

regamedll/dlls/client.cpp, regamedll/dlls/gamerules.h, regamedll/dlls/multiplay_gamerules.cpp, regamedll/dlls/player.cpp, regamedll/dlls/util.cpp, regamedll/dlls/util.h
This PR omits the logic that changes the player's introduction camera to it (the same), which forces a rather annoying change of angles because there is no behavior that verifies if there is more than just one trigger_camera.
- `m_bMapHasCameras` member from `CSGameRules` changed type to `int`, which is the same as `BOOL` internally, and it counts the number of `trigger_camera` entities in the map.
- It is cached once on `ClientPutInServer`.
- Default value in the construction of the `CSGameRules` class is now -1 (ToDo: I don't think I need to enclose that with the fixes macro).
- `m_fIntroCamTime` is assigned to 0.0 if there's just only one `trigger_camera`, so it wont force an unnecesary camera updating every 6 seconds. A simple condition was added in the related thinking function …
=> Avoid intro camera switching when only 1 trigger_camera available

regamedll/dlls/API/CSEntity.cpp, regamedll/dlls/API/CSPlayer.cpp, regamedll/public/regamedll/API/CSEntity.h, regamedll/public/regamedll/regamedll_api.h
A few lines changed/added just for readability 👍
=> Tiny API code clean

regamedll/dlls/animation.cpp, regamedll/engine/studio.h
- Updated studio.h header using ReHLDS files:
- Limits increased according to engine ones
- Added missing structures (in case of)
- `g_pBoneTransform` size using magic number changed to a defined number
=> Update studio.h constants

regamedll/public/regamedll/API/CSEntity.h
=> Initialize m_pevLastInflictor to nullptr to avoid garbage memory

regamedll/dlls/player.cpp, regamedll/dlls/player.h, regamedll/public/regamedll/API/CSPlayer.h, regamedll/public/regamedll/regamedll_const.h
The only way to "naturally" GIB on death for players is reaching -9000 health points. This PR adds a CCSPlayer member that controls that value individually per player. It defaults to -9000.
=> Add member m_iGibDamageThreshold to control GIB damage threshold

README.md, dist/game.cfg, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/gamerules.h, regamedll/dlls/multiplay_gamerules.cpp, regamedll/dlls/player.cpp
from: https://totalcsgo.com/commands/mpdefuserallocation
```cpp
// Give defuser on player spawn
// 0 - No free defusers (default behavior)
// 1 - Random players
// 2 - All players
//
// Default value: "0"
mp_defuser_allocation  "0"
```
=> New ConVar: `mp_defuser_allocation`

regamedll/common/const.h, regamedll/dlls/client.cpp, regamedll/dlls/player.cpp, regamedll/dlls/weapons.cpp, regamedll/dlls/weapons.h
Now that reapi can register custom ammo, I added proper support for secondary ammo.
Also, I added some extra EF_ flags that I requested a time ago, so I made it by myself.
Any stupid typo I made please let me know.
Compiled in Debian and tested in ubuntu, works fine.
=> Support for secondary ammo and extra EF_ flags

regamedll/dlls/cbase.cpp
Fixes #918 - it demonstrates how abrupt punchangle change was done when getting shot using tactical shield.
=> Fix excessive punchangle when getting shield shot

regamedll/dlls/triggers.cpp, regamedll/dlls/triggers.h, regamedll/extra/Toolkit/GameDefinitionFile/regamedll-cs.fgd
=> Add trigger_teleport landmark

regamedll/dlls/weapons.cpp
This seems redundant but avoids an API call from ApplyMultiDamage at the first AddMultiDamage call since there's no pEntity, forcing a call to this function without success. This expects to straighten subplugin's hooks to work as expected since ApplyMultiDamage should be called at the end of the MultiDamage routine, or when other entity is hit (penetration or shotgun spread).  
In case of a weapon with no penetration (usp, for example) a simple FireBullets3 call will result in:
- ClearMultiDamage (null pEntity)
- TraceAttack pre (null pEntity)
- AddMultiDamage pre (null pEntity)
- **ApplyMultiDamage (null pEntity -> no TakeDamage call inside)**
- _pEntity assigned to a valid entity_
- AddMultiDamage post (valid pEntity)
- TraceAttack post (valid pEntity)
- ApplyMultiDamage (valid pEntity …
=> Fix ApplyMultiDamage duplicated call on MultiDamage routine

regamedll/dlls/gamerules.h, regamedll/dlls/multiplay_gamerules.cpp
This solves some problems detected during the testing of the hook "RG_CSGameRules_SendDeathMessage" and is totally linked to https://github.com/s1lentq/reapi/pull/305
=> Fix `SendDeathMessage` kill rarity flags and transform to VFUNC

regamedll/game_shared/bot/nav_area.cpp
Thanks to @CH3L74 for finding the bug on zm_flood map
video: https://youtu.be/Lu0yzVpQoAE
P.S: `Very Sleepy` software [helps](https://stackoverflow.com/a/8104036) to find where is a bug http://www.codersnotes.com/sleepy/
=> `CNavArea::ComputeApproachAreas()`:  fix hang on `*.nav` generating

regamedll/dlls/ammo.cpp, regamedll/dlls/multiplay_gamerules.cpp, regamedll/dlls/weapons.cpp
Items that were created without the `SF_NORESPAWN` flag can work normally (like HL: Deathmatch items)
video: https://www.youtube.com/watch?v=TsfiMZ0RuPU
=> Fix: `ammo`/`weapons` respawn behavior

regamedll/dlls/weapons.cpp, regamedll/dlls/wpn_shared/wpn_awp.cpp, regamedll/dlls/wpn_shared/wpn_deagle.cpp, regamedll/dlls/wpn_shared/wpn_elite.cpp, regamedll/dlls/wpn_shared/wpn_fiveseven.cpp, regamedll/dlls/wpn_shared/wpn_g3sg1.cpp, regamedll/dlls/wpn_shared/wpn_glock18.cpp, regamedll/dlls/wpn_shared/wpn_m3.cpp, regamedll/dlls/wpn_shared/wpn_p228.cpp, regamedll/dlls/wpn_shared/wpn_scout.cpp, regamedll/dlls/wpn_shared/wpn_sg550.cpp, regamedll/dlls/wpn_shared/wpn_usp.cpp, regamedll/dlls/wpn_shared/wpn_xm1014.cpp
This modification extends the usage and hooking of the `CBasePlayerWeapon::KickBack` function which handles recoil control. In summary, the changes made were:
- Punchangle boundary fix: If your punchangles are already in a high value, shooting will clamp punchangle according to the lateral/up max angle value. This PR fixes that by ignoring if already having punchangle in an out-of-boundary value.
- `KickBack` params expanded: You can not force a lateral or up max angle value, or force a direction change probability.
By the mentioned points:
- Now every weapon uses `KickBack`. All other weapons just punches vertically, so `KickBack` needed a readjustment for those basic cases. 
- This is useful for API consumption and event handling, so you can alter/handle every weapon recoil in a simple …
=> API: KickBack function extension

regamedll/dlls/player.cpp
Not really useful, discovered while testing on 3rd party plugins that ObjectCaps was being called unnecessarily more than once per entity
=> Cache ObjectCaps call inside PlayerUse

regamedll/dlls/player.cpp
By mistake I added an unnecessary and harmful check (from pr #419) commit https://github.com/s1lentq/ReGameDLL_CS/pull/419/commits/d43c4083e73f9d7b99b17ea2fe5817509fab70c5
=> fix mp_kill_filled_spawn

regamedll/dlls/bot/cs_bot.cpp, regamedll/dlls/bot/cs_bot.h, regamedll/dlls/bot/cs_bot_chatter.cpp, regamedll/dlls/bot/cs_bot_chatter.h, regamedll/dlls/bot/cs_bot_init.cpp, regamedll/dlls/bot/cs_bot_update.cpp, regamedll/dlls/bot/cs_bot_vision.cpp
previously unused chatter on both 1.6 and czero but is used on cs source
=> Bot Chatter: Bots will react to enemy snipers presence

regamedll/dlls/client.cpp
Avoid unnecessary use of say_team in FFA mode. Only for CT and T, Spectators can still use say_team.
Fix ignoremsg command behaviour in FFA mode (you can still see "enemies" message)
Change Host_Say's teamonly parameter local value to make say_team behaviour work like a simple say message.
Use CSGameRules::PlayerRelationship function instead of directly checking team indexes
=> Team Say refactory/enhancement

regamedll/dlls/bot/states/cs_bot_buy.cpp
bots can't buy sec ammo if preferred pistol (ex. "WeaponPreference = deagle" in BotProfile.db)
=> Fix buy bots sec ammo

README.md, dist/game.cfg, regamedll/dlls/bot/cs_bot.h, regamedll/dlls/bot/cs_bot_init.cpp, regamedll/dlls/bot/cs_bot_init.h
Finally the bots don't sit around after a couple of losses :D
=> add new  cvar "bot_excellent_morale"

README.md, dist/game.cfg, regamedll/dlls/game.cpp, regamedll/dlls/game.h, regamedll/dlls/player.cpp
for example:
mp_ct_default_weapons_primary "famas mp5 aug m4a1 awp m4a1 famas mp5"
mp_t_default_weapons_primary "galil mp5 sg552 ak47 awp ak47 galil mp5"
mp_ct_default_weapons_secondary "usp glock18 fiveseven glock18 deagle usp p228"
mp_t_default_weapons_secondary "usp glock18 elites glock18 deagle usp p228"
mp_default_weapons_random 1
_*some weapons are duplicated so they drop more often_
=> New ConVar `mp_default_weapons_random`

regamedll/dlls/ggrenade.cpp
Implement AddPoints for awarding frags after the C4 explodes or is defused. Currently, when a round is won, players need to wait until the next round to see their final score after successfully planting or defusing. With the integration of `mp_round_restart_delay`, the round ending can last longer, providing an important window for a scoreboard update.
Change frag incrementing inside `CGrenade::C4Think` and `CGrenade::DefuseBombEnd` to use AddPoints (which is currently unused) instead of directly incrementing the member variable.
This also allows better handling of frag awarding by hooking the (virtual) AddPoints method, as used by AMXX's hamsandwich module.
Note: In AddPoints, we allow negative scores because mp_give_c4_frags can be negative. This is not particularly important, but it is …
=> Use AddPoints when exploding/defusing C4 bombs to properly update scoreboard

regamedll/dlls/ggrenade.cpp
To spawn a grenade, you must specify an owner. In cases where you want to spawn a non-owned grenade, you currently need to create a dummy entity to achieve this.
Add conditionals to each creation function to allow a null owner to be passed as a parameter. Same as #899.
A few lines removed, which had no purpose
=> Allow null owner on grenade spawning

regamedll/dlls/cbase.cpp
Optimize `TraceBleed`, which is called when a player is shot, by reducing unnecessary `TraceLine` calls for blood decal placement. In high-fire-rate modded servers (e.g., zombie mods), this can otherwise consume unnecessary resources.
Move the 1/3 probability check to the start of the loop in `TraceBleed` and continue early when it fails, avoiding the cost of computing jitter and calling `TraceLine` in those cases.
=> Optimize TraceBleed to skip unnecessary TraceLine calls

regamedll/dlls/weapontype.cpp
The default maximum values ​​for the grenade `MaxClip` were incorrectly assigned in `GetItemInfo`. This was a simple, harmless typo. This also fixes the values ​​for knife and C4, only in the `WeaponInfo` structure, which has no repercussions. 
Modify `gunClipSize` values from `g_weaponInfo_default` array on NoClip weapons.
The first appearance of these incorrect values ​​dates back to 2016 in the commit https://github.com/rehlds/ReGameDLL_CS/commit/183a9f674c79ffa2ba6c7fc7be9306f6e1d1729f
Specific lines:
https://github.com/rehlds/ReGameDLL_CS/blob/24744cd75ab019dad41ab6f154ad5ec3c115f672/regamedll/dlls/wpn_shared/wpn_flashbang.cpp#L44
https://github.com/rehlds/ReGameDLL_CS/blob/24744cd75ab019dad41ab6f154ad5ec3c115f672/regamedll/dlls/wpn_shared/wpn_hegrenade.cpp#L47 …
=> Fixed incorrect default iMaxClip value for grenades

regamedll/dlls/multiplay_gamerules.cpp
a small change in the logic in multiplay_gamerules.cpp SelectDefaultTeam() regarding the selection of a priority team for a player.
In the case of equal numbers of players in teams, the player is selected a team based on the number of victories of the teams. However, this does not always work correctly  Pr: when the map is played for a long time (it can be only dust2, pool_day, etc..) the map changes rarely, the score in the teams can go over 1000+ and the difference between the teams can be, for example, 300, in fact, this method becomes useless because the priority will always work in one direction, even if the players have been different for a long time. I suggest checking the number of consecutive wins, so we can more accurately determine which team will be stronger.
=> Improve SelectDefaultTeam() logic
